# module figure_review_agent.py
import os
from typing import Any, Dict, Optional

# Compatible package/script import for SimpleChatLLM
try:
    from ..llm.agent_client import SimpleChatLLM
except Exception:
    try:
        from researcher.analysis.agent.llm.agent_client import SimpleChatLLM  # type: ignore
    except Exception:
        from src.researcher.analysis.agent.agent_client import SimpleChatLLM  # type: ignore
from pathlib import Path
import re
import json
from datetime import datetime, timezone
import argparse
from researcher.analysis.common import resolve_project_paths


class FigureReviewAgent:
    """
    Basic Figure Review Agent:
    - Input an image path + prompt
    - Call a multimodal LLM to return suggestions (text or strict JSON)
    """

    def __init__(
        self,
        config_name: Optional[str] = None,
        config_path: Optional[str] = None,
        system_prompt: Optional[str] = None,
    ) -> None:
        cfg_name = config_name or os.environ.get("ANALYSIS_PLOT_MODEL_NAME") or os.environ.get("ONESIM_PLOT_MODEL_NAME") or os.environ.get("STAGE2_PLOT_MODEL_NAME") or os.environ.get("ONESIM_MODEL_NAME") or "claude-sonnet-4-5-20250929"
        cfg_path = config_path or os.environ.get("ONESIM_MODEL_CONFIG") or "config/model_config.json"
        self.llm = SimpleChatLLM(config_name=cfg_name, config_path=cfg_path)
        self.system_prompt = (
            system_prompt
            or "You are a professional visualization reviewer. Provide concise, actionable suggestions."
        )

    def review_image_text(
        self,
        image_path: str,
        prompt: str,
        temperature: Optional[float] = 0.3,
    ) -> str:
        """
        Return textual suggestions.
        """
        user_text = prompt or "Please review this figure and provide constructive suggestions."
        return self.llm.chat_multimodal(
            user_text=user_text,
            image_paths=[image_path],
            system_prompt=(
                self.system_prompt
                + " Note: This figure is generated by code written by a large language model; consider common code-gen visualization issues (empty plots, misaligned axes, wrong aggregations, mislabeled units)."
            ),
            temperature=temperature,
        )

    def review_image_json(
        self,
        image_path: str,
        prompt: str = "",
        temperature: Optional[float] = 0.2,
    ) -> Dict[str, Any]:
        """
        Return strict JSON including suggestions, issues, and decision (keep or abort).
        """
        sp = (
            "Return ONLY valid JSON with top-level keys: "
            "'data_useful' (boolean), 'action' ('keep'|'abort'), "
            "'issues' (list of strings), 'suggestions' (list of strings), "
            "'expected_changes' (list of strings describing concrete changes such as 'steps>=10', 'curves>=3', 'has_legend'), "
            "'data_checks' (list of strings specifying data integrity checks that should pass, e.g., 'loaded_real_data', 'non_empty', 'step_parsed_int', 'value_range_valid'), "
            "'visual_checks' (list of strings specifying visualization health checks that should pass, e.g., 'has_axes_labels', 'has_legend', 'sufficient_ticks', 'non_blank_image'). "
            "Decision rule: keep if data_useful is true and only minor issues; "
            "abort if data_useful is false or data integrity problems are found. "
            "The figure is generated by code written by a large language model; "
            "consider common generation issues: empty plot, wrong aggregation, mislabeled axes/units, incorrect ranges, duplicated lines/bars, placeholder or synthetic data. "
            "No extra text or markdown."
        )
        user_text = prompt or "Review the figure, determine data usefulness, decide keep or abort, list issues and suggestions."
        return self.llm.chat_multimodal_json(
            user_text=user_text,
            image_paths=[image_path],
            system_prompt=sp,
            temperature=temperature,
        )


def assemble_project_reviews(project_name: str, prompt: Optional[str] = None) -> Dict[str, Any]:
    figures_dir = Path(resolve_project_paths(project_name)["figures_dir"])
    if not figures_dir.exists():
        raise FileNotFoundError(f"Path does not exist: {figures_dir}")

    matched: list[Path] = []
    try:
        for p in figures_dir.glob("fig*.png"):
            name = p.name
            m = re.match(r"^fig(\d+)\.png$", name)
            if m:
                matched.append(p)
    except Exception:
        matched = []

    if not matched:
        i = 1
        while True:
            candidate = figures_dir / f"fig{i}.png"
            if candidate.exists():
                matched.append(candidate)
                i += 1
            else:
                break

    matched.sort(key=lambda x: int(re.match(r"^fig(\d+)\.png$", x.name).group(1)))

    agent = FigureReviewAgent()
    results: list[Dict[str, Any]] = []
    for p in matched:
        try:
            review = agent.review_image_json(
                str(p),
                prompt or "Please provide improvement suggestions for layout, labels, colors, and readability, and point out existing issues.",
            )
        except Exception as e:
            review = {"suggestions": [], "issues": [f"Review failed: {e}"]}

        output = {
            "project_name": project_name,
            "figure_file": p.name,
            "figure_path": str(p),
            "review": review,
            "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        }

        out_path = p.with_name(f"{p.stem}.review.json")
        try:
            with open(out_path, "w", encoding="utf-8") as f:
                json.dump(output, f, ensure_ascii=False, indent=2)
        except Exception:
            pass

        results.append(output)

    return {"count": len(results), "figures_dir": str(figures_dir), "results": results}


def main() -> int:
    parser = argparse.ArgumentParser(description="FigureReviewAgent project-level reviewer")
    parser.add_argument("project_name", help="Project name under projects/{project_name}")
    parser.add_argument("--prompt", default=None, help="Optional review prompt override")
    args = parser.parse_args()

    project_name = args.project_name
    prompt = args.prompt

    try:
        summary = assemble_project_reviews(project_name, prompt)
    except FileNotFoundError as e:
        print(f"[ERROR] {e}")
        return 2
    except Exception as e:
        print(f"[ERROR] Review failed: {e}")
        return 1

    # Print and persist overall summary under figures dir
    try:
        figures_dir = Path(resolve_project_paths(project_name)["figures_dir"])
        figures_dir.mkdir(parents=True, exist_ok=True)
        out_path = figures_dir / "figure_reviews.summary.json"
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(summary, f, ensure_ascii=False, indent=2)
        print(json.dumps(summary, ensure_ascii=False, indent=2))
        print(f"[INFO] Wrote summary -> {out_path}")
    except Exception as e:
        print(json.dumps(summary, ensure_ascii=False, indent=2))
        print(f"[WARN] Failed to write summary: {e}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
